### PR TITLE
Fix javascript not work

### PR DESCRIPTION
**Pull request by zhangshifeng**

### CODE REVIEW

**Comment by jonesde** [comment]
In which browser did you see an issue with this? Which screen did you see this on, or more generally what are the steps to reproduce?

**Comment by jonesde** [comment]
BTW, in general I've tried to avoid these jQuery init wrappers and unless there is a good reason for them I would prefer to avoid them.

**Comment by zhangshifeng** [comment]
My browser is Chrome 54.0.2840.98
You can see this issue in any page that uses `dynamic-options`. 
For example: https://demo.moqui.org/apps/example/Example/EditExample

**Comment by zhangshifeng** [comment]
I try to use below code replace of  jQuery init wrapper, it's working fine. 

```ftl
<#assign afterScreenScript>
    <#list depNodeList as depNode>
    $("#<@fieldIdByName depNode["@field"]/>").on('change', function() { populate_${id}(); });
    </#list>
    populate_${id}();
</#assign>
<#t>${sri.appendToScriptWriter(afterScreenScript)}
```

**Comment by jonesde** [comment]
It looks like the issue is that on the EditExample screen the exampleTypeEnumId field is before the statusId field but has a depends-on to the statusId field. This is an uncommon scenario as usually a drop-down dependent on another field comes after that field (which is why this hasn't come up as an issue outside the example component).

I'll think more on this, whether it is worth making this change. There are some advantages to the cleaner JS code that the default HTML macros now produce, though this is a downside...

**Comment by zhangshifeng** [comment]
Sounds make sense. So I'll close this.
BTW, I try to exchange  `exampleTypeEnumId`  and `statusId` positions, it's working fine.

**Pull request closed without merging**
