### PR TITLE
Add l10n libraries for validating on browser with same locale as on server

### PR DESCRIPTION
**Pull request by jenshp**
This is not a really nice patch so it goes separate ways from other l10n changes, and I think we have discussed it previously.
I have been using these changes for several months now and it is the only way I have been able to use artifacts like HiveMind without generating unexpected failures like multiplying reported hours by a hundred for some time entries.
The main point is that without these changes, it is impossible to handle decimal digits while using locales with comma as decimal separator. I know it is not the best solution, but it is the solution provided by the chosen library (jquery-validate) so the validation is locale-aware. Another solution would be to use another validation library that has a better approach for l10n, but the current status of using a validation library that only works with some locales does not work.

### CODE REVIEW

**Comment by jenshp** [comment]
This is actually a re-submission of pull request https://github.com/moqui/moqui-runtime/pull/93

**Comment by jonesde** [comment]
My thought on this is similar to before, this is messy and heavy for a small thing and there must be a better way. The jquery-validate library is used commonly enough, and is used in the html and vuet screen macros quite a bit, but maybe there is an alternative that handles localization better.

I appreciate your work on this and submitting the pull request but I'm still hesitant about using this approach in the main code base. It adds a lot of maintenance overhead for a fairly small thing, but maybe it is the best (or only workable) approach and is what we'll end up doing. I'd like to see thoughts from others on this topic but not sure that is likely to happen, I don't think anyone even looks at pull requests other than their own.

Doing a little bit more review there are some things in this that I would change, or would like changed. One is the location and name of the service file which doesn't follow patterns in moqui-framework or other services like those in mantle-usl. Also it's a small thing but it's best if services use only methods that are in the public interfaces in the framework API, ie ec.10n.getLocale() is an internal method that is not in the L10nFacade.java interface. The better one to use is ec.user.getLocale(), ie 'ec.user.locale' in groovy.

Again maybe this is the best approach and I'll think on it over coming and revisit it to maybe finally get it in, I know it is an area that causes issues for those who are using the OOTB moqui-runtime and need better language and formatting/etc validation support for certain parts of the world.

**Comment by jonesde** [comment]
Please see commit 5918e92. This is a compromise that uses cdnjs URLs instead of local copies.

Note that this relies on moqui-framework commit 3147f4ca to handle full URLs treated as subscreen paths, needed for convenience in this case so the header template doesn't need to detect a full URL vs subscreen path.

Let me know if this works for your case or if you run into any issues.

**Comment by jonesde** [comment]
Have you updated moqui-framework and done a build? That is why I mentioned this relies on the changes in moqui-framework commit 3147f4ca.

**Comment by jenshp** [comment]
Sorry, I thought I did but I checked a different branch. Yes, including those changes in moqui-framework works OK for me, have not found any problems. Thanks for your time.

**Pull request closed without merging**
