### PR TITLE
feat: enable /status for health check and docker host heartbeat check

### PR DESCRIPTION
**Pull request by jenshp**
Enable /status transition for selected IPs (127.0.0.1 for docker health check, obtain docker host IP from environment variable).

### CODE REVIEW

**Comment by jonesde** [comment]
The configuration should follow the normal convention that also helps document options available. To do this add a default-property element to MoquiDefaultConf.xml with a property name and a default value or no value. It looks like a good default value in this case would "127.0.0.1". 

Anything defined as a default-property in the merged conf XML file is automatically searched for in the Java properties and system env vars, and if found set as a Java property or if not found and there is a default in the conf XML file then the Java property is set to that default value. In other words with a default-property defined in your code you can just look for a Java property with that name.

**Comment by jenshp** [comment]
Thanks David, I added the property in the file, and changed the name so it is more consistent with other properties that are being used.

**Comment by jonesde** [comment]
This looks good technically but the property name 'instance_docker_host_ips' seems odd... it is used to allow access to /status but the name implies something completely different, actually I'm not sure what it implies. Either way this doesn't really have anything to do with Docker and is applicable for other hosting environments as well.

Maybe something like 'webapp_status_ips'?

One way I think of this sort of thing is what will documentation, training, support, etc look like? This may not bother other people but for my part I hate having to say things like 'it is called X but really means Y' or 'oh, you're looking for Y, look at X because that was built as part of Z so that's the context you have to consider when looking for it and yes that means you have to know a lot about the history of the software and not just it's current state in order to effectively use it'. I do end up having to say such things a fair amount, and that is how I know I've messed up a design.

**Comment by jenshp** [comment]
You are right, the name was set thinking of the application motivating its implementation, but it can have a wider variety of uses. There goes a change updating the name.

**Pull request merged**
