### PR TITLE
Update javascript libraries affected by vulnerabilities

### PR DESCRIPTION
**Pull request by Tellan**
I did some basic testing, and nothing was a major-version upgrade so everything seems to be fine. Bootstrap 4 has a lot of breaking changes so that won't go in without a lot of fixes.

- bootstrap https://snyk.io/vuln/npm:bootstrap
- jquery https://snyk.io/vuln/npm:jquery
- jstree https://snyk.io/vuln/npm:jstree
- momentjs https://snyk.io/vuln/npm:moment
- vue https://snyk.io/vuln/npm:vue

### CODE REVIEW

**Comment by jonesde** [comment]
Thank you for looking into this and the notes on the vulnerabilities.

Just to set expectations... when updating these (especially lower level ones like jquery, vue, and bootstrap) every XML Screen and Form widget needs to be tested. There are lots of them and some have lots of variations depending on options selected. There are also various screens that have custom JS, additional JS libraries, etc that need to tested with the updates (the wiki screens, the various screens that use Chart.js, ElFinder screen, etc). Many updates in the past have gone smoothly but there have been dozens of issues over the years just from updating JS libraries.

If a few people convince me they have done thorough testing I might just do some light testing and merge this, but otherwise it will be a while before I can do that. This is likely to take at least a half day, and possibly much more for any issues uncovered. I also typically review JS library release notes before updating, and check for compatibility of higher level JS libraries and such, the intent of that effort being to get the latest version or the most recent without significant issues, and a set of versions that work well together. From a quick glance it looks like these are mostly minor updates, but I haven't looked thoroughly.

One thing Moqui does not have right now that would be helpful for this is in-browser automated tests (ie using selenium or whatever). Those sorts of tests are time consuming to create and maintain so have been out of reach for the current actively contributing Moqui community.

And yes, it will take some work to migrate to Bootstrap 4, lots of changes there! The new PopRestStore component is using Bootstrap 4, and the moqui-runtime stuff needs to be updated sooner or later for XML Screen based apps, but yeah, that will take more effort.

**Comment by Tellan** [comment]
I understand. It's a requirement for us right now, so we'll be using our fork in our systems until we get some real testing done. Just wanted to make this available in case anyone wanted to integrate it into their runtime or help with the testing. Our alpha systems get used pretty regularly so we'll report back here if we notice any problems.

**Comment by jonesde** [comment]
Have you had a chance to test this more? I was hoping others would also pitch in, but might not be worth waiting for. I looked at this again briefly and chances are these are lower risk updates anyway and I'm considering doing a bit more testing myself and then merging... and let more comprehensive testing happen the 'natural' way (ie people update and then complain if anything breaks).

**Comment by Tellan** [comment]
We've had it deployed in our test and production environment since the PR and haven't had any complaints. I can't say that we've tested every component, but we regularly use Popc order/store/product/parties and the entity screens.

**Pull request merged**
